<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>Titanis.TBO.Smb2.PowerShell</AssemblyName>
    <RootNamespace>Titanis.Tbo.Smb2.PowerShell</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Format.ps1xml" />
    <None Remove="Titanis.TBO.Smb2.psd1" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\..\tools\net\smb2\Smb2Client\FileAttributeFormatter.cs" Link="FileAttributeFormatter.cs" />
    <Compile Include="..\..\tools\net\smb2\Smb2Client\StringHelper.cs" Link="StringHelper.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Format.ps1xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Titanis.TBO.Smb2.psd1">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="PowerShellStandard.Library" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\base\Titanis.Cli\Titanis.Cli.csproj" />
    <ProjectReference Include="..\base\Titanis.Winterop.FileInfo\Titanis.Winterop.FileInfo.csproj" />
    <ProjectReference Include="..\net\Titanis.DceRpc\Titanis.DceRpc.csproj" />
    <ProjectReference Include="..\net\msrpc\Titanis.Msrpc.Mslsar\Titanis.Msrpc.Mslsar.csproj" />
    <ProjectReference Include="..\net\Titanis.Smb2\Titanis.Smb2.csproj" />
    <ProjectReference Include="..\security\Titanis.Security.Kerberos\Titanis.Security.Kerberos.csproj" />
    <ProjectReference Include="..\security\Titanis.Security.Ntlm\Titanis.Security.Ntlm.csproj" />
    <ProjectReference Include="..\security\Titanis.Security.Spnego\Titanis.Security.Spnego.csproj" />
    <ProjectReference Include="..\security\Titanis.Security\Titanis.Security.csproj" />
  </ItemGroup>

</Project>
